name: Build

on:
  push:
    branches:
      - "**"

jobs:
  release:
    uses: mathisdt/workflows/.github/workflows/earthly.yaml@master
    with:
      pattern-to-release: web-address-book-enhanced-*.jar
    secrets: inherit
